-R src Coqine
-I src
CONSTRUCTORS_PLUGIN = "src/coqine_plugin.cma"
CONSTRUCTORS_PLUGINOPT = "src/coqine_plugin.cmxs"
src/utils.mli
src/dedukti.mli
src/error.mli
src/info.mli
src/name.mli
src/tsorts.mli
src/terms.mli
src/inductives.mli
src/modules.mli
src/libraries.mli
src/utils.ml
src/dedukti.ml
src/error.ml
src/info.ml
src/name.ml
src/univparse.ml4
src/tsorts.ml
src/terms.ml
src/inductives.ml
src/modules.ml
src/libraries.ml
src/commands.ml4
src/coqine_plugin.mllib
src/Coqine.v
