(** Translation of Coq libraries *)

let translate_library out dir_path =
  let qualid = Libnames.qualid_of_dirpath dir_path in  
  let module_path = Nametab.locate_module qualid in
  let module_body = Global.lookup_module module_path in
  let info = Info.init out dir_path in
  Dedukti.print out (Dedukti.comment "This file was automatically generated by Coqine.");
  Dedukti.print out (Dedukti.command "NAME" [Name.translate_dir_path dir_path]);
  Modules.translate_module_body info (Global.env ()) module_body;
  Dedukti.print out (Dedukti.comment "End of translation")

